declare module Ammo {
  declare class btSliderConstraint {
    constructor();
    constructor(rbB: btRigidBody, frameInB: btTransform, useLinearReferenceFrameA: boolean);
    constructor(rbA: btRigidBody, rbB: btRigidBody, frameInA: btTransform, frameInB: btTransform, useLinearReferenceFrameA: boolean);


    calculateTransforms(transA: btTransform, transB: btTransform): void;
    calculateSerializeBufferSize(): number;
    getInfo2NonVirtual(info: btConstraintInfo2, transA: btTransform, transB: btTransform, linVelA: btVector3, linVelB: btVector3, rbAinvMass: number, rbBinvMass: number): void;
    getRigidBodyA(): btRigidBody;
    getRigidBodyB(): btRigidBody;
    getCalculatedTransformA(): btTransform;
    getCalculatedTransformB(): btTransform;
    getFrameOffsetA(): btTransform;
    getFrameOffsetB(): btTransform;
    getFrameOffsetA(): btTransform;
    getFrameOffsetB(): btTransform;
    getLowerLinLimit(): number;
    getUpperLinLimit(): number;
    getLowerAngLimit(): number;
    getUpperAngLimit(): number;
    getUseLinearReferenceFrameA(): boolean;
    getSoftnessDirLin(): number;
    getRestitutionDirLin(): number;
    getDampingDirLin(): number;
    getSoftnessDirAng(): number;
    getRestitutionDirAng(): number;
    getDampingDirAng(): number;
    getSoftnessLimLin(): number;
    getRestitutionLimLin(): number;
    getDampingLimLin(): number;
    getParam(num: number, axis: number): number;
    getRestitutionLimAng(): number;
    getDampingLimAng(): number;
    getSoftnessOrthoLin(): number;
    getRestitutionOrthoLin(): number;
    getDampingOrthoLin(): number;
    getSoftnessOrthoAng(): number;
    getRestitutionOrthoAng(): number;
    getDampingOrthoAng(): number;
    getInfo1(info: btConstraintInfo1): void;
    getPoweredLinMotor(): boolean;
    getTargetLinMotorVelocity(): number;
    getMaxLinMotorForce(): number;
    getPoweredAngMotor(): boolean;
    getTargetAngMotorVelocity(): number;
    getMaxAngMotorForce(): number;
    getLinearPos(): number;
    getAngularPos(): number;
    getSolveLinLimit(): boolean;
    getLinDepth(): number;
    getSolveAngLimit(): boolean;
    getAngDepth(): number;
    getInfo1NonVirtual(info: btConstraintInfo1): void;
    getInfo2(info: btConstraintInfo2): void;
    getFlags(): number;
    getAncorInA(): btVector3;
    getAncorInB(): btVector3;
    getUseFrameOffset(): boolean;
    getSoftnessLimAng(): number;
    setSoftnessOrthoAng(softnessOrthoAng: number): void;
    setRestitutionOrthoAng(restitutionOrthoAng: number): void;
    setDampingOrthoAng(dampingOrthoAng: number): void;
    setPoweredLinMotor(onOff: boolean): void;
    setUpperLinLimit(upperLimit: number): void;
    setTargetLinMotorVelocity(targetLinMotorVelocity: number): void;
    setLowerLinLimit(lowerLimit: number): void;
    setMaxLinMotorForce(maxLinMotorForce: number): void;
    setLowerAngLimit(lowerLimit: number): void;
    setPoweredAngMotor(onOff: boolean): void;
    serialize(dataBuffer: void, serializer: btSerializer): string;
    setTargetAngMotorVelocity(targetAngMotorVelocity: number): void;
    setSoftnessDirLin(softnessDirLin: number): void;
    setMaxAngMotorForce(maxAngMotorForce: number): void;
    setRestitutionDirLin(restitutionDirLin: number): void;
    setDampingDirLin(dampingDirLin: number): void;
    setUpperAngLimit(upperLimit: number): void;
    setRestitutionDirAng(restitutionDirAng: number): void;
    setDampingDirAng(dampingDirAng: number): void;
    setSoftnessLimLin(softnessLimLin: number): void;
    setRestitutionLimLin(restitutionLimLin: number): void;
    setDampingLimLin(dampingLimLin: number): void;
    setSoftnessLimAng(softnessLimAng: number): void;
    setRestitutionLimAng(restitutionLimAng: number): void;
    setDampingLimAng(dampingLimAng: number): void;
    setSoftnessOrthoLin(softnessOrthoLin: number): void;
    setRestitutionOrthoLin(restitutionOrthoLin: number): void;
    setUseFrameOffset(frameOffsetOnOff: boolean): void;
    setFrames(frameA: btTransform, frameB: btTransform): void;
    setParam(num: number, value: number, axis: number): void;
    setDampingOrthoLin(dampingOrthoLin: number): void;
    setSoftnessDirAng(softnessDirAng: number): void;
    testAngLimits(): void;
    testLinLimits(): void;
  }
}
