declare module Ammo {
  declare class btVector3 {
    constructor();
    constructor();
    constructor(_x: number, _y: number, _z: number);
    get_operator(): btVector3;	set_operator(value: btVector3): btVector3;
    get_operator(): btVector3;	set_operator(value: btVector3): btVector3;
    get_operator(): btVector3;	set_operator(value: btVector3): btVector3;
    get_operator(): btVector3;	set_operator(value: btVector3): btVector3;
    dot(v: btVector3): number;
    length2(): number;
    length(): number;
    norm(): number;
    safeNorm(): number;
    distance2(v: btVector3): number;
    distance(v: btVector3): number;
    safeNormalize(): btVector3;
    normalize(): btVector3;
    normalized(): btVector3;
    rotate(wAxis: btVector3, angle: number): btVector3;
    angle(v: btVector3): number;
    absolute(): btVector3;
    cross(v: btVector3): btVector3;
    triple(v1: btVector3, v2: btVector3): number;
    minAxis(): number;
    maxAxis(): number;
    furthestAxis(): number;
    closestAxis(): number;
    setInterpolate3(v0: btVector3, v1: btVector3, rt: number): void;
    lerp(v: btVector3, t: number): btVector3;
    get_operator(): btVector3;	set_operator(value: btVector3): btVector3;
    getX(): number;
    getY(): number;
    getZ(): number;
    setX(_x: number): void;
    setY(_y: number): void;
    setZ(_z: number): void;
    setW(_w: number): void;
    x(): number;
    y(): number;
    z(): number;
    w(): number;
    get_btScalar(): operator;	set_btScalar(value: operator): operator;
    get_const(): operator;	set_const(value: operator): operator;
    get_operator(): boolean;	set_operator(value: boolean): boolean;
    get_operator(): boolean;	set_operator(value: boolean): boolean;
    setMax(other: btVector3): void;
    setMin(other: btVector3): void;
    setValue(_x: number, _y: number, _z: number): void;
    getSkewSymmetricMatrix(v0: btVector3, v1: btVector3, v2: btVector3): void;
    setZero(): void;
    isZero(): boolean;
    fuzzyZero(): boolean;
    serialize(btVector3Data: struct): void;
    deSerialize(btVector3DoubleData: struct): void;
    deSerialize(btVector3FloatData: struct): void;
    serializeFloat(btVector3FloatData: struct): void;
    deSerializeFloat(btVector3FloatData: struct): void;
    serializeDouble(btVector3DoubleData: struct): void;
    deSerializeDouble(btVector3DoubleData: struct): void;
    maxDot(array: btVector3, array_count: number, dotOut: number): number;
    minDot(array: btVector3, array_count: number, dotOut: number): number;
    dot3(v0: btVector3, v1: btVector3, v2: btVector3): btVector3;
    get_m_floats(): number;	set_m_floats(value: number): number;
  }
}
