declare module Ammo {
  declare class btWorldImporter {
    constructor(world: btDynamicsWorld);
    deleteAllData(): void;
    setVerboseMode(verboseMode: number): void;
    getVerboseMode(): number;
    setImporterFlags(importerFlags: number): void;
    getImporterFlags(): number;
    getNumCollisionShapes(): number;
    getCollisionShapeByIndex(index: number): btCollisionShape;
    getNumRigidBodies(): number;
    getRigidBodyByIndex(index: number): btCollisionObject;
    getNumConstraints(): number;
    getConstraintByIndex(index: number): btTypedConstraint;
    getNumBvhs(): number;
    getBvhByIndex(index: number): btOptimizedBvh;
    getNumTriangleInfoMaps(): number;
    getTriangleInfoMapByIndex(index: number): btTriangleInfoMap;
    getCollisionShapeByName(name: string): btCollisionShape;
    getRigidBodyByName(name: string): btRigidBody;
    getConstraintByName(name: string): btTypedConstraint;
    getNameForPointer(ptr: void): string;
    setDynamicsWorldInfo(gravity: btVector3, solverInfo: btContactSolverInfo): void;
    createRigidBody(isDynamic: boolean, mass: number, startTransform: btTransform, shape: btCollisionShape, bodyName: string): btRigidBody;
    createCollisionObject(startTransform: btTransform, shape: btCollisionShape, bodyName: string): btCollisionObject;
    createPlaneShape(planeNormal: btVector3, planeConstant: number): btCollisionShape;
    createBoxShape(halfExtents: btVector3): btCollisionShape;
    createSphereShape(radius: number): btCollisionShape;
    createCapsuleShapeX(radius: number, height: number): btCollisionShape;
    createCapsuleShapeY(radius: number, height: number): btCollisionShape;
    createCapsuleShapeZ(radius: number, height: number): btCollisionShape;
    createCylinderShapeX(radius: number, height: number): btCollisionShape;
    createCylinderShapeY(radius: number, height: number): btCollisionShape;
    createCylinderShapeZ(radius: number, height: number): btCollisionShape;
    createConeShapeX(radius: number, height: number): btCollisionShape;
    createConeShapeY(radius: number, height: number): btCollisionShape;
    createConeShapeZ(radius: number, height: number): btCollisionShape;
    get_class(): virtual;	set_class(value: virtual): virtual;
    createBvhTriangleMeshShape(trimesh: btStridingMeshInterface, bvh: btOptimizedBvh): btBvhTriangleMeshShape;
    createConvexTriangleMeshShape(trimesh: btStridingMeshInterface): btCollisionShape;
    createGimpactShape(trimesh: btStridingMeshInterface): btGImpactMeshShape;
    createStridingMeshInterfaceData(interfaceData: btStridingMeshInterfaceData): btStridingMeshInterfaceData;
    get_class(): virtual;	set_class(value: virtual): virtual;
    get_class(): virtual;	set_class(value: virtual): virtual;
    get_class(): virtual;	set_class(value: virtual): virtual;
    get_class(): virtual;	set_class(value: virtual): virtual;
    createMeshInterface(meshData: btStridingMeshInterfaceData): btTriangleIndexVertexArray;
    createOptimizedBvh(): btOptimizedBvh;
    createTriangleInfoMap(): btTriangleInfoMap;
    createPoint2PointConstraint(rbA: btRigidBody, rbB: btRigidBody, pivotInA: btVector3, pivotInB: btVector3): btPoint2PointConstraint;
    createPoint2PointConstraint(rbA: btRigidBody, pivotInA: btVector3): btPoint2PointConstraint;
    createHingeConstraint(rbA: btRigidBody, rbB: btRigidBody, rbAFrame: btTransform, rbBFrame: btTransform, useReferenceFrameA: boolean): btHingeConstraint;
    createHingeConstraint(rbA: btRigidBody, rbAFrame: btTransform, useReferenceFrameA: boolean): btHingeConstraint;
    createConeTwistConstraint(rbA: btRigidBody, rbB: btRigidBody, rbAFrame: btTransform, rbBFrame: btTransform): btConeTwistConstraint;
    createConeTwistConstraint(rbA: btRigidBody, rbAFrame: btTransform): btConeTwistConstraint;
    createGeneric6DofConstraint(rbA: btRigidBody, rbB: btRigidBody, frameInA: btTransform, frameInB: btTransform, useLinearReferenceFrameA: boolean): btGeneric6DofConstraint;
    createGeneric6DofConstraint(rbB: btRigidBody, frameInB: btTransform, useLinearReferenceFrameB: boolean): btGeneric6DofConstraint;
    createGeneric6DofSpringConstraint(rbA: btRigidBody, rbB: btRigidBody, frameInA: btTransform, frameInB: btTransform, useLinearReferenceFrameA: boolean): btGeneric6DofSpringConstraint;
    createGeneric6DofSpring2Constraint(rbA: btRigidBody, rbB: btRigidBody, frameInA: btTransform, frameInB: btTransform, rotateOrder: number): btGeneric6DofSpring2Constraint;
    createSliderConstraint(rbA: btRigidBody, rbB: btRigidBody, frameInA: btTransform, frameInB: btTransform, useLinearReferenceFrameA: boolean): btSliderConstraint;
    createSliderConstraint(rbB: btRigidBody, frameInB: btTransform, useLinearReferenceFrameA: boolean): btSliderConstraint;
    createGearConstraint(rbA: btRigidBody, rbB: btRigidBody, axisInA: btVector3, axisInB: btVector3, ratio: number): btGearConstraint;
  }
}
